### ISSUE TITLE
hi，data can not download😭

### ISSUE THREAD

**Issue by jun0wanan** [hyounghk/VideoQADenseCapFrameGate-ACL2020#1]

**Comment by hyounghk** [comment]
Hi, thank you for your interest. Can you let me know which data you mean?

**Comment by jun0wanan** [comment]
roberta_dcap.zip  this！！


I have try a lot of methods to download it ... But because it is too big(170G),we can not download it very easy..Our country do not allow us to search in google . We usually use a app to download,but I find if the data is to big,it will be very difficult...Can you upload other place  ? I really thank you!!! Hope to receive from you again!!!













在 2020-05-26 10:40:28，"hyounghk" <notifications@github.com> 写道：

Hi, thank you for your interest. Can you let me know which data you mean?

**Comment by hyounghk** [comment]
Hi, sorry for late response.
I split the dense_cap feature (30G*6) and uploaded in the following link:
https://drive.google.com/drive/folders/1oE-hJN4N6GB7gFwNxsOq96QMRXgK0_wM?usp=sharing

Thanks.

**Comment by Liubinggunzu** [comment]
> Hi, sorry for late response.
> I split the dense_cap feature (30G*6) and uploaded in the following link:
> https://drive.google.com/drive/folders/1oE-hJN4N6GB7gFwNxsOq96QMRXgK0_wM?usp=sharing
> 
> Thanks.

Hi, I downloaded these 6 files but I don't know how to uncompress the included 5 files named 'roberta_dcap_split.z01', 'roberta_dcap_split.z02', 'roberta_dcap_split.z03', 'roberta_dcap_split.z04', 'roberta_dcap_split.z05'.

**Comment by Liubinggunzu** [comment]
> Hi, sorry for late response.
> I split the dense_cap feature (30G*6) and uploaded in the following link:
> https://drive.google.com/drive/folders/1oE-hJN4N6GB7gFwNxsOq96QMRXgK0_wM?usp=sharing
> 
> Thanks.

Hi, I downloaded these splitted data, but I get this error when I use this command: unzip roberta_dcap_split.zip. 

file #12640:  bad zipfile offset (local header sig):  3082557304

**Comment by hyounghk** [comment]
Hi, can you try this?
https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux

**Comment by Liubinggunzu** [comment]
> Hi, can you try this?
> https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux

Great! Thanks for your code sharing and reply! 
In my server with Ubuntu 16.04.4, I use these commands:
>>cat roberta_dcap_split.* >roberta_dcap_split.zip
>>zip -FF roberta_dcap_split.zip --out roberta_dcap_split_full.zip
>>7z x roberta_dcap_split_full.zip
Problem solved!

**Comment by Liubinggunzu** [comment]
> Hi, can you try this?
> https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux

Thanks for your reply!
I use these commands and problem solved:
>cat roberta_dcap_split.z0* > ~/roberta_dcap_split.zip
>zip -FF roberta_dcap_split.zip --out roberta_dcap_split-full.zip
unzip roberta_dcap_split-full.zip

**Comment by BNU-Wu** [comment]
hello，@jun0wanan ！Have you downloaded the data? I am also domestic, and I still cannot download the data provided by the author. Have you downloaded it yet?

**Comment by BNU-Wu** [comment]
hello，@Liubinggunzu  ！  Have you downloaded the data? I am also domestic, and I still cannot download the data provided by the author. Have you downloaded it yet?

**Comment by jun0wanan** [comment]
We have no idea .. Because the author didn't give bbox of  object of frame .. You can not see the attention .. 
















在 2020-09-30 10:16:49，"BNU-Wu" <notifications@github.com> 写道：

hello，@Liubinggunzu ！ Have you downloaded the data? I am also domestic, and I still cannot download the data provided by the author. Have you downloaded it yet?
