### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by jun0wanan** [hyounghk/VideoQADenseCapFrameGate-ACL2020#3]

**Comment by jun0wanan** [comment]
hi，can you give us？

**Comment by hyounghk** [comment]
Sorry, I don't have the box feature.

**Comment by jun0wanan** [comment]
hi,thank you your reply!
        But your paper shows the weight image of BBox ..
















在 2020-09-24 11:17:58，"hyounghk" <notifications@github.com> 写道：

Sorry, I don't have the box feature.

**Comment by hyounghk** [comment]
Sorry, I was a bit confused. Actually we did not use the box feature for our model, but used it just for the visualization. We borrowed the box feature from the author of the EMNLP 2018 TVQA paper (https://arxiv.org/abs/1809.01696). 
Please download it from here: https://drive.google.com/file/d/1UtIoG3IT2E3Y--j8AC4fu_tqtP6gAON3/view?usp=sharing.
And, please cite the EMNLP 2018 TVQA paper as well when you use it.
