### ISSUE TITLE
Could you provide the function "mkdirp" in config.py ?

### ISSUE THREAD

**Issue by bty1992** [hyounghk/VideoQADenseCapFrameGate-ACL2020#4]
It is the source code that "from utils.utils import mkdirp, load_json, save_json_pretty, make_zipfile" in "config.py" in line 7. However, I failed to find out the function "mkdirp". It would be appreciated if you could provide the function.

**Comment by hyounghk** [comment]
Sorry for late response. 
mkdirp is just 'os.makedirs()' call. So you can use this instead.
Or, you can manually create the corresponding directory in advance.

**Comment by bty1992** [comment]
Really appreciate it！
